name: CI

on:
    # Triggers the workflow on push events but only for the "dev" branch
    push:
        branches: ['dev']

jobs:
    build:
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3

            - name: Install graphviz
              run: sudo apt install -y graphviz

            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'npm'
            - run: npm install
            - run: npm run docs

            - name: Git Auto Commit
              uses: stefanzweifel/git-auto-commit-action@v4.14.1
              with:
                  # Commit message: in case we need to skip azure pipeline we should include [skip azurepipelines]. This needs to be tested though.
                  commit_message: Update documentation
                  push_options: --force
