#
# This reusable workflow is used to build a TypeScript project, run tests using vitest, and perform SonarCloud analysis.
# It is designed to be called from other workflows.
#
#
# HOW TO USE:
#
# To call this reusable workflow, copy the code between === lines to a new workflow file,
# uncomment and adjust "uses" as needed (use the latest tag available).
# ======================================================================
#
# name: xxxxx
#
# on:
#   pull_request:
#     branches:
#       # every PR targetting main branch
#       - main
#     types:
#       # on labeled and unlabeled to validate labels,
#       # on closed to create tag when PR is merged
#       types: [labeled, unlabeled, closed]
#
# jobs:
#   build-n-test:
#     uses: OutSystems/rd.github-reusable-workflows/.github/workflows/ts-build-project@vVersionHash
#     with:
#         github-ref: ${{ github.ref }}
#         run-vitest: true        # or false, depending on whether you want to run Vitest tests
#         run-sonarcloud: true    # or false, depending on whether you want to run SonarCloud analysis
#     secrets:
#         OSUI_AZURE_CLIENT_ID: ${{ secrets.OSUI_AZURE_CLIENT_ID }}
#         OSUI_AZURE_TENANT_ID: ${{ secrets.OSUI_AZURE_TENANT_ID }}
#         OSUI_AZURE_SUBSCRIPTION_ID: ${{ secrets.OSUI_AZURE_SUBSCRIPTION_ID }}
#
# ======================================================================
#
name: Build TS project
description: 'Build, run Vitest tests, and SonarCloud in a TypeScript project.'
on:
    workflow_call:
        inputs:
            github-ref:
                description: 'GitHub reference to be used as base to create a new one to generate and be published.'
                type: string
                required: true
            run-vitest:
                description: 'Defines if Vitest tests should be run or not.'
                type: boolean
                required: false
                default: false
            run-sonarcloud:
                description: 'Defines if SonarCloud analysis should be run or not.'
                type: boolean
                required: false
                default: false
        secrets:
            OSUI_AZURE_CLIENT_ID:
                description: 'Azure Client ID for authentication'
                required: true
            OSUI_AZURE_TENANT_ID:
                description: 'Azure Tenant ID for authentication'
                required: true
            OSUI_AZURE_SUBSCRIPTION_ID:
                description: 'Azure Subscription ID for authentication'
                required: true

jobs:
    build-n-test:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps: 
            - name: üì• Checkout main branch
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  ref: ${{ inputs.github-ref }}

            - name: üîê Azure login
              #uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-login@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7
              uses: ./.github/actions/az-login
              with:
                  client-id: ${{ secrets.OSUI_AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.OSUI_AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.OSUI_AZURE_SUBSCRIPTION_ID }}

            - name: üîë Get Azure DevOps token
              id: get-devOps-token
              #uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-keyvault-get@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7
              uses: ./.github/actions/az-keyvault-get
              with:
                  key-name: o11odc-github-ado-token-prd

            - name: üîë Get SonarCloud token
              id: get-sonarcloud-token
              if: ${{ inputs.run-sonarcloud == true }}
              #uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-keyvault-get@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7
              uses: ./.github/actions/az-keyvault-get
              with:
                  key-name: o11odc-github-sonarcloud-token-prd

            - name: ‚≠ï Connect to OutSystems Environment
              shell: bash
              run: npx @outsystems/assistant login --token ${{ steps.get-devOps-token.outputs.az-keyvault-value }}

            - name: üï∏Ô∏è Install dependencies
              run: npm install

            - name: üèóÔ∏è Run build
              run: npm run build

            - name: üß™ Run Vitest with Code Coverage
              if: ${{ inputs.run-vitest == true }}
              run: npm run test:coverage

            - name: üìä Run sonarcloud analysis
              #uses: OutSystems/rd.github-reusable-workflows/.github/actions/run-sonarcloud@3df86e14f6ad0021256077f91c43eca3f73d3b57 #v2.0.6
              uses: ./.github/actions/run-sonarcloud
              if: ${{ inputs.run-sonarcloud == true }}
              with:
                  sonarcloud-token: ${{ steps.get-sonarcloud-token.outputs.az-keyvault-value }}
